//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetFirstCustomerDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstCustomerData", ReplyAction="*")]
        WebService.ServiceReference1.GetFirstCustomerDataResponse GetFirstCustomerData(WebService.ServiceReference1.GetFirstCustomerDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstCustomerData", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.GetFirstCustomerDataResponse> GetFirstCustomerDataAsync(WebService.ServiceReference1.GetFirstCustomerDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFirstCustomerDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFirstCustomerData", Namespace="http://tempuri.org/", Order=0)]
        public WebService.ServiceReference1.GetFirstCustomerDataRequestBody Body;
        
        public GetFirstCustomerDataRequest() {
        }
        
        public GetFirstCustomerDataRequest(WebService.ServiceReference1.GetFirstCustomerDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetFirstCustomerDataRequestBody {
        
        public GetFirstCustomerDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFirstCustomerDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFirstCustomerDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService.ServiceReference1.GetFirstCustomerDataResponseBody Body;
        
        public GetFirstCustomerDataResponse() {
        }
        
        public GetFirstCustomerDataResponse(WebService.ServiceReference1.GetFirstCustomerDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFirstCustomerDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService.ServiceReference1.ArrayOfString GetFirstCustomerDataResult;
        
        public GetFirstCustomerDataResponseBody() {
        }
        
        public GetFirstCustomerDataResponseBody(WebService.ServiceReference1.ArrayOfString GetFirstCustomerDataResult) {
            this.GetFirstCustomerDataResult = GetFirstCustomerDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebService.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebService.ServiceReference1.WebService1Soap>, WebService.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.GetFirstCustomerDataResponse WebService.ServiceReference1.WebService1Soap.GetFirstCustomerData(WebService.ServiceReference1.GetFirstCustomerDataRequest request) {
            return base.Channel.GetFirstCustomerData(request);
        }
        
        public WebService.ServiceReference1.ArrayOfString GetFirstCustomerData() {
            WebService.ServiceReference1.GetFirstCustomerDataRequest inValue = new WebService.ServiceReference1.GetFirstCustomerDataRequest();
            inValue.Body = new WebService.ServiceReference1.GetFirstCustomerDataRequestBody();
            WebService.ServiceReference1.GetFirstCustomerDataResponse retVal = ((WebService.ServiceReference1.WebService1Soap)(this)).GetFirstCustomerData(inValue);
            return retVal.Body.GetFirstCustomerDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.GetFirstCustomerDataResponse> WebService.ServiceReference1.WebService1Soap.GetFirstCustomerDataAsync(WebService.ServiceReference1.GetFirstCustomerDataRequest request) {
            return base.Channel.GetFirstCustomerDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.GetFirstCustomerDataResponse> GetFirstCustomerDataAsync() {
            WebService.ServiceReference1.GetFirstCustomerDataRequest inValue = new WebService.ServiceReference1.GetFirstCustomerDataRequest();
            inValue.Body = new WebService.ServiceReference1.GetFirstCustomerDataRequestBody();
            return ((WebService.ServiceReference1.WebService1Soap)(this)).GetFirstCustomerDataAsync(inValue);
        }
    }
}
