//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace presentation.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Products", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Products : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private int SupplierIDField;
        
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityPerUnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SupplierID {
            get {
                return this.SupplierIDField;
            }
            set {
                if ((this.SupplierIDField.Equals(value) != true)) {
                    this.SupplierIDField = value;
                    this.RaisePropertyChanged("SupplierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string QuantityPerUnit {
            get {
                return this.QuantityPerUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityPerUnitField, value) != true)) {
                    this.QuantityPerUnitField = value;
                    this.RaisePropertyChanged("QuantityPerUnit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orders", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Orders : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipRegionField;
        
        private System.DateTime OrderDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ShipVia {
            get {
                return this.ShipViaField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipViaField, value) != true)) {
                    this.ShipViaField = value;
                    this.RaisePropertyChanged("ShipVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ShipName {
            get {
                return this.ShipNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipNameField, value) != true)) {
                    this.ShipNameField = value;
                    this.RaisePropertyChanged("ShipName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ShipAddress {
            get {
                return this.ShipAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipAddressField, value) != true)) {
                    this.ShipAddressField = value;
                    this.RaisePropertyChanged("ShipAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ShipRegion {
            get {
                return this.ShipRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipRegionField, value) != true)) {
                    this.ShipRegionField = value;
                    this.RaisePropertyChanged("ShipRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customers", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContactTitle {
            get {
                return this.ContactTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactTitleField, value) != true)) {
                    this.ContactTitleField = value;
                    this.RaisePropertyChanged("ContactTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name productname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetsProductID", ReplyAction="*")]
        presentation.ServiceReference1.GetsProductIDResponse GetsProductID(presentation.ServiceReference1.GetsProductIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetsProductID", ReplyAction="*")]
        System.Threading.Tasks.Task<presentation.ServiceReference1.GetsProductIDResponse> GetsProductIDAsync(presentation.ServiceReference1.GetsProductIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductssResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductss", ReplyAction="*")]
        presentation.ServiceReference1.GetProductssResponse GetProductss(presentation.ServiceReference1.GetProductssRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductss", ReplyAction="*")]
        System.Threading.Tasks.Task<presentation.ServiceReference1.GetProductssResponse> GetProductssAsync(presentation.ServiceReference1.GetProductssRequest request);
        
        // CODEGEN: Generating message contract since element name customerid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersByCustomerr", ReplyAction="*")]
        presentation.ServiceReference1.GetOrdersByCustomerrResponse GetOrdersByCustomerr(presentation.ServiceReference1.GetOrdersByCustomerrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersByCustomerr", ReplyAction="*")]
        System.Threading.Tasks.Task<presentation.ServiceReference1.GetOrdersByCustomerrResponse> GetOrdersByCustomerrAsync(presentation.ServiceReference1.GetOrdersByCustomerrRequest request);
        
        // CODEGEN: Generating message contract since element name GetFirstCustomerDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstCustomerData", ReplyAction="*")]
        presentation.ServiceReference1.GetFirstCustomerDataResponse GetFirstCustomerData(presentation.ServiceReference1.GetFirstCustomerDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstCustomerData", ReplyAction="*")]
        System.Threading.Tasks.Task<presentation.ServiceReference1.GetFirstCustomerDataResponse> GetFirstCustomerDataAsync(presentation.ServiceReference1.GetFirstCustomerDataRequest request);
        
        // CODEGEN: Generating message contract since element name GetLastCustomersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastCustomers", ReplyAction="*")]
        presentation.ServiceReference1.GetLastCustomersResponse GetLastCustomers(presentation.ServiceReference1.GetLastCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<presentation.ServiceReference1.GetLastCustomersResponse> GetLastCustomersAsync(presentation.ServiceReference1.GetLastCustomersRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNextCustomerr", ReplyAction="*")]
        presentation.ServiceReference1.GetNextCustomerrResponse GetNextCustomerr(presentation.ServiceReference1.GetNextCustomerrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNextCustomerr", ReplyAction="*")]
        System.Threading.Tasks.Task<presentation.ServiceReference1.GetNextCustomerrResponse> GetNextCustomerrAsync(presentation.ServiceReference1.GetNextCustomerrRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadPreviousCustomerr", ReplyAction="*")]
        presentation.ServiceReference1.LoadPreviousCustomerrResponse LoadPreviousCustomerr(presentation.ServiceReference1.LoadPreviousCustomerrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadPreviousCustomerr", ReplyAction="*")]
        System.Threading.Tasks.Task<presentation.ServiceReference1.LoadPreviousCustomerrResponse> LoadPreviousCustomerrAsync(presentation.ServiceReference1.LoadPreviousCustomerrRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetsProductIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetsProductID", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.GetsProductIDRequestBody Body;
        
        public GetsProductIDRequest() {
        }
        
        public GetsProductIDRequest(presentation.ServiceReference1.GetsProductIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetsProductIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productname;
        
        public GetsProductIDRequestBody() {
        }
        
        public GetsProductIDRequestBody(string productname) {
            this.productname = productname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetsProductIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetsProductIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.GetsProductIDResponseBody Body;
        
        public GetsProductIDResponse() {
        }
        
        public GetsProductIDResponse(presentation.ServiceReference1.GetsProductIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetsProductIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetsProductIDResult;
        
        public GetsProductIDResponseBody() {
        }
        
        public GetsProductIDResponseBody(int GetsProductIDResult) {
            this.GetsProductIDResult = GetsProductIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductssRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductss", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.GetProductssRequestBody Body;
        
        public GetProductssRequest() {
        }
        
        public GetProductssRequest(presentation.ServiceReference1.GetProductssRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductssRequestBody {
        
        public GetProductssRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductssResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductssResponse", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.GetProductssResponseBody Body;
        
        public GetProductssResponse() {
        }
        
        public GetProductssResponse(presentation.ServiceReference1.GetProductssResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductssResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public presentation.ServiceReference1.Products[] GetProductssResult;
        
        public GetProductssResponseBody() {
        }
        
        public GetProductssResponseBody(presentation.ServiceReference1.Products[] GetProductssResult) {
            this.GetProductssResult = GetProductssResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersByCustomerrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersByCustomerr", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.GetOrdersByCustomerrRequestBody Body;
        
        public GetOrdersByCustomerrRequest() {
        }
        
        public GetOrdersByCustomerrRequest(presentation.ServiceReference1.GetOrdersByCustomerrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersByCustomerrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customerid;
        
        public GetOrdersByCustomerrRequestBody() {
        }
        
        public GetOrdersByCustomerrRequestBody(string customerid) {
            this.customerid = customerid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersByCustomerrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersByCustomerrResponse", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.GetOrdersByCustomerrResponseBody Body;
        
        public GetOrdersByCustomerrResponse() {
        }
        
        public GetOrdersByCustomerrResponse(presentation.ServiceReference1.GetOrdersByCustomerrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersByCustomerrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public presentation.ServiceReference1.Orders[] GetOrdersByCustomerrResult;
        
        public GetOrdersByCustomerrResponseBody() {
        }
        
        public GetOrdersByCustomerrResponseBody(presentation.ServiceReference1.Orders[] GetOrdersByCustomerrResult) {
            this.GetOrdersByCustomerrResult = GetOrdersByCustomerrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFirstCustomerDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFirstCustomerData", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.GetFirstCustomerDataRequestBody Body;
        
        public GetFirstCustomerDataRequest() {
        }
        
        public GetFirstCustomerDataRequest(presentation.ServiceReference1.GetFirstCustomerDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetFirstCustomerDataRequestBody {
        
        public GetFirstCustomerDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFirstCustomerDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFirstCustomerDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.GetFirstCustomerDataResponseBody Body;
        
        public GetFirstCustomerDataResponse() {
        }
        
        public GetFirstCustomerDataResponse(presentation.ServiceReference1.GetFirstCustomerDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFirstCustomerDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public presentation.ServiceReference1.Customers GetFirstCustomerDataResult;
        
        public GetFirstCustomerDataResponseBody() {
        }
        
        public GetFirstCustomerDataResponseBody(presentation.ServiceReference1.Customers GetFirstCustomerDataResult) {
            this.GetFirstCustomerDataResult = GetFirstCustomerDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastCustomers", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.GetLastCustomersRequestBody Body;
        
        public GetLastCustomersRequest() {
        }
        
        public GetLastCustomersRequest(presentation.ServiceReference1.GetLastCustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLastCustomersRequestBody {
        
        public GetLastCustomersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastCustomersResponse", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.GetLastCustomersResponseBody Body;
        
        public GetLastCustomersResponse() {
        }
        
        public GetLastCustomersResponse(presentation.ServiceReference1.GetLastCustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLastCustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public presentation.ServiceReference1.Customers GetLastCustomersResult;
        
        public GetLastCustomersResponseBody() {
        }
        
        public GetLastCustomersResponseBody(presentation.ServiceReference1.Customers GetLastCustomersResult) {
            this.GetLastCustomersResult = GetLastCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNextCustomerrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNextCustomerr", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.GetNextCustomerrRequestBody Body;
        
        public GetNextCustomerrRequest() {
        }
        
        public GetNextCustomerrRequest(presentation.ServiceReference1.GetNextCustomerrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNextCustomerrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        public GetNextCustomerrRequestBody() {
        }
        
        public GetNextCustomerrRequestBody(string ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNextCustomerrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNextCustomerrResponse", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.GetNextCustomerrResponseBody Body;
        
        public GetNextCustomerrResponse() {
        }
        
        public GetNextCustomerrResponse(presentation.ServiceReference1.GetNextCustomerrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNextCustomerrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public presentation.ServiceReference1.Customers GetNextCustomerrResult;
        
        public GetNextCustomerrResponseBody() {
        }
        
        public GetNextCustomerrResponseBody(presentation.ServiceReference1.Customers GetNextCustomerrResult) {
            this.GetNextCustomerrResult = GetNextCustomerrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadPreviousCustomerrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadPreviousCustomerr", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.LoadPreviousCustomerrRequestBody Body;
        
        public LoadPreviousCustomerrRequest() {
        }
        
        public LoadPreviousCustomerrRequest(presentation.ServiceReference1.LoadPreviousCustomerrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadPreviousCustomerrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public LoadPreviousCustomerrRequestBody() {
        }
        
        public LoadPreviousCustomerrRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadPreviousCustomerrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadPreviousCustomerrResponse", Namespace="http://tempuri.org/", Order=0)]
        public presentation.ServiceReference1.LoadPreviousCustomerrResponseBody Body;
        
        public LoadPreviousCustomerrResponse() {
        }
        
        public LoadPreviousCustomerrResponse(presentation.ServiceReference1.LoadPreviousCustomerrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadPreviousCustomerrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public presentation.ServiceReference1.Customers LoadPreviousCustomerrResult;
        
        public LoadPreviousCustomerrResponseBody() {
        }
        
        public LoadPreviousCustomerrResponseBody(presentation.ServiceReference1.Customers LoadPreviousCustomerrResult) {
            this.LoadPreviousCustomerrResult = LoadPreviousCustomerrResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : presentation.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<presentation.ServiceReference1.WebService1Soap>, presentation.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        presentation.ServiceReference1.GetsProductIDResponse presentation.ServiceReference1.WebService1Soap.GetsProductID(presentation.ServiceReference1.GetsProductIDRequest request) {
            return base.Channel.GetsProductID(request);
        }
        
        public int GetsProductID(string productname) {
            presentation.ServiceReference1.GetsProductIDRequest inValue = new presentation.ServiceReference1.GetsProductIDRequest();
            inValue.Body = new presentation.ServiceReference1.GetsProductIDRequestBody();
            inValue.Body.productname = productname;
            presentation.ServiceReference1.GetsProductIDResponse retVal = ((presentation.ServiceReference1.WebService1Soap)(this)).GetsProductID(inValue);
            return retVal.Body.GetsProductIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<presentation.ServiceReference1.GetsProductIDResponse> presentation.ServiceReference1.WebService1Soap.GetsProductIDAsync(presentation.ServiceReference1.GetsProductIDRequest request) {
            return base.Channel.GetsProductIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<presentation.ServiceReference1.GetsProductIDResponse> GetsProductIDAsync(string productname) {
            presentation.ServiceReference1.GetsProductIDRequest inValue = new presentation.ServiceReference1.GetsProductIDRequest();
            inValue.Body = new presentation.ServiceReference1.GetsProductIDRequestBody();
            inValue.Body.productname = productname;
            return ((presentation.ServiceReference1.WebService1Soap)(this)).GetsProductIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        presentation.ServiceReference1.GetProductssResponse presentation.ServiceReference1.WebService1Soap.GetProductss(presentation.ServiceReference1.GetProductssRequest request) {
            return base.Channel.GetProductss(request);
        }
        
        public presentation.ServiceReference1.Products[] GetProductss() {
            presentation.ServiceReference1.GetProductssRequest inValue = new presentation.ServiceReference1.GetProductssRequest();
            inValue.Body = new presentation.ServiceReference1.GetProductssRequestBody();
            presentation.ServiceReference1.GetProductssResponse retVal = ((presentation.ServiceReference1.WebService1Soap)(this)).GetProductss(inValue);
            return retVal.Body.GetProductssResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<presentation.ServiceReference1.GetProductssResponse> presentation.ServiceReference1.WebService1Soap.GetProductssAsync(presentation.ServiceReference1.GetProductssRequest request) {
            return base.Channel.GetProductssAsync(request);
        }
        
        public System.Threading.Tasks.Task<presentation.ServiceReference1.GetProductssResponse> GetProductssAsync() {
            presentation.ServiceReference1.GetProductssRequest inValue = new presentation.ServiceReference1.GetProductssRequest();
            inValue.Body = new presentation.ServiceReference1.GetProductssRequestBody();
            return ((presentation.ServiceReference1.WebService1Soap)(this)).GetProductssAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        presentation.ServiceReference1.GetOrdersByCustomerrResponse presentation.ServiceReference1.WebService1Soap.GetOrdersByCustomerr(presentation.ServiceReference1.GetOrdersByCustomerrRequest request) {
            return base.Channel.GetOrdersByCustomerr(request);
        }
        
        public presentation.ServiceReference1.Orders[] GetOrdersByCustomerr(string customerid) {
            presentation.ServiceReference1.GetOrdersByCustomerrRequest inValue = new presentation.ServiceReference1.GetOrdersByCustomerrRequest();
            inValue.Body = new presentation.ServiceReference1.GetOrdersByCustomerrRequestBody();
            inValue.Body.customerid = customerid;
            presentation.ServiceReference1.GetOrdersByCustomerrResponse retVal = ((presentation.ServiceReference1.WebService1Soap)(this)).GetOrdersByCustomerr(inValue);
            return retVal.Body.GetOrdersByCustomerrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<presentation.ServiceReference1.GetOrdersByCustomerrResponse> presentation.ServiceReference1.WebService1Soap.GetOrdersByCustomerrAsync(presentation.ServiceReference1.GetOrdersByCustomerrRequest request) {
            return base.Channel.GetOrdersByCustomerrAsync(request);
        }
        
        public System.Threading.Tasks.Task<presentation.ServiceReference1.GetOrdersByCustomerrResponse> GetOrdersByCustomerrAsync(string customerid) {
            presentation.ServiceReference1.GetOrdersByCustomerrRequest inValue = new presentation.ServiceReference1.GetOrdersByCustomerrRequest();
            inValue.Body = new presentation.ServiceReference1.GetOrdersByCustomerrRequestBody();
            inValue.Body.customerid = customerid;
            return ((presentation.ServiceReference1.WebService1Soap)(this)).GetOrdersByCustomerrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        presentation.ServiceReference1.GetFirstCustomerDataResponse presentation.ServiceReference1.WebService1Soap.GetFirstCustomerData(presentation.ServiceReference1.GetFirstCustomerDataRequest request) {
            return base.Channel.GetFirstCustomerData(request);
        }
        
        public presentation.ServiceReference1.Customers GetFirstCustomerData() {
            presentation.ServiceReference1.GetFirstCustomerDataRequest inValue = new presentation.ServiceReference1.GetFirstCustomerDataRequest();
            inValue.Body = new presentation.ServiceReference1.GetFirstCustomerDataRequestBody();
            presentation.ServiceReference1.GetFirstCustomerDataResponse retVal = ((presentation.ServiceReference1.WebService1Soap)(this)).GetFirstCustomerData(inValue);
            return retVal.Body.GetFirstCustomerDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<presentation.ServiceReference1.GetFirstCustomerDataResponse> presentation.ServiceReference1.WebService1Soap.GetFirstCustomerDataAsync(presentation.ServiceReference1.GetFirstCustomerDataRequest request) {
            return base.Channel.GetFirstCustomerDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<presentation.ServiceReference1.GetFirstCustomerDataResponse> GetFirstCustomerDataAsync() {
            presentation.ServiceReference1.GetFirstCustomerDataRequest inValue = new presentation.ServiceReference1.GetFirstCustomerDataRequest();
            inValue.Body = new presentation.ServiceReference1.GetFirstCustomerDataRequestBody();
            return ((presentation.ServiceReference1.WebService1Soap)(this)).GetFirstCustomerDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        presentation.ServiceReference1.GetLastCustomersResponse presentation.ServiceReference1.WebService1Soap.GetLastCustomers(presentation.ServiceReference1.GetLastCustomersRequest request) {
            return base.Channel.GetLastCustomers(request);
        }
        
        public presentation.ServiceReference1.Customers GetLastCustomers() {
            presentation.ServiceReference1.GetLastCustomersRequest inValue = new presentation.ServiceReference1.GetLastCustomersRequest();
            inValue.Body = new presentation.ServiceReference1.GetLastCustomersRequestBody();
            presentation.ServiceReference1.GetLastCustomersResponse retVal = ((presentation.ServiceReference1.WebService1Soap)(this)).GetLastCustomers(inValue);
            return retVal.Body.GetLastCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<presentation.ServiceReference1.GetLastCustomersResponse> presentation.ServiceReference1.WebService1Soap.GetLastCustomersAsync(presentation.ServiceReference1.GetLastCustomersRequest request) {
            return base.Channel.GetLastCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<presentation.ServiceReference1.GetLastCustomersResponse> GetLastCustomersAsync() {
            presentation.ServiceReference1.GetLastCustomersRequest inValue = new presentation.ServiceReference1.GetLastCustomersRequest();
            inValue.Body = new presentation.ServiceReference1.GetLastCustomersRequestBody();
            return ((presentation.ServiceReference1.WebService1Soap)(this)).GetLastCustomersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        presentation.ServiceReference1.GetNextCustomerrResponse presentation.ServiceReference1.WebService1Soap.GetNextCustomerr(presentation.ServiceReference1.GetNextCustomerrRequest request) {
            return base.Channel.GetNextCustomerr(request);
        }
        
        public presentation.ServiceReference1.Customers GetNextCustomerr(string ID) {
            presentation.ServiceReference1.GetNextCustomerrRequest inValue = new presentation.ServiceReference1.GetNextCustomerrRequest();
            inValue.Body = new presentation.ServiceReference1.GetNextCustomerrRequestBody();
            inValue.Body.ID = ID;
            presentation.ServiceReference1.GetNextCustomerrResponse retVal = ((presentation.ServiceReference1.WebService1Soap)(this)).GetNextCustomerr(inValue);
            return retVal.Body.GetNextCustomerrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<presentation.ServiceReference1.GetNextCustomerrResponse> presentation.ServiceReference1.WebService1Soap.GetNextCustomerrAsync(presentation.ServiceReference1.GetNextCustomerrRequest request) {
            return base.Channel.GetNextCustomerrAsync(request);
        }
        
        public System.Threading.Tasks.Task<presentation.ServiceReference1.GetNextCustomerrResponse> GetNextCustomerrAsync(string ID) {
            presentation.ServiceReference1.GetNextCustomerrRequest inValue = new presentation.ServiceReference1.GetNextCustomerrRequest();
            inValue.Body = new presentation.ServiceReference1.GetNextCustomerrRequestBody();
            inValue.Body.ID = ID;
            return ((presentation.ServiceReference1.WebService1Soap)(this)).GetNextCustomerrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        presentation.ServiceReference1.LoadPreviousCustomerrResponse presentation.ServiceReference1.WebService1Soap.LoadPreviousCustomerr(presentation.ServiceReference1.LoadPreviousCustomerrRequest request) {
            return base.Channel.LoadPreviousCustomerr(request);
        }
        
        public presentation.ServiceReference1.Customers LoadPreviousCustomerr(string id) {
            presentation.ServiceReference1.LoadPreviousCustomerrRequest inValue = new presentation.ServiceReference1.LoadPreviousCustomerrRequest();
            inValue.Body = new presentation.ServiceReference1.LoadPreviousCustomerrRequestBody();
            inValue.Body.id = id;
            presentation.ServiceReference1.LoadPreviousCustomerrResponse retVal = ((presentation.ServiceReference1.WebService1Soap)(this)).LoadPreviousCustomerr(inValue);
            return retVal.Body.LoadPreviousCustomerrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<presentation.ServiceReference1.LoadPreviousCustomerrResponse> presentation.ServiceReference1.WebService1Soap.LoadPreviousCustomerrAsync(presentation.ServiceReference1.LoadPreviousCustomerrRequest request) {
            return base.Channel.LoadPreviousCustomerrAsync(request);
        }
        
        public System.Threading.Tasks.Task<presentation.ServiceReference1.LoadPreviousCustomerrResponse> LoadPreviousCustomerrAsync(string id) {
            presentation.ServiceReference1.LoadPreviousCustomerrRequest inValue = new presentation.ServiceReference1.LoadPreviousCustomerrRequest();
            inValue.Body = new presentation.ServiceReference1.LoadPreviousCustomerrRequestBody();
            inValue.Body.id = id;
            return ((presentation.ServiceReference1.WebService1Soap)(this)).LoadPreviousCustomerrAsync(inValue);
        }
    }
}
